apiVersion: v1
#声明PVC
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  #PVC 的资源要求
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  #和动态配置有关
  storageClassName: ""
