apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-dp
spec:
  #指定 StorageClass
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
