apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  containers:
  - image: luksa/fortune:env
    #
    env:
    - name: INTERVAL
      valueFrom:
        #引用 ConfigMap fortune-config 的 sleep-interval
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    #挂在 configMap 到对应目录
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    #挂在 configMap 到对应目录
    - name: config
      mountPath: /tmp/whole-fortune-config-volume
      readOnly: true
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
  #使用 ConfigMap volume
  - name: config
    configMap:
      name: fortune-config
